import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import config from "@/config/config";
import MainLayout from "@/Layout/MainLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: config.appName,
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <div className= "flex flex-col min-h-screen bg-slate-100 dark:bg-[#121212]">
       <MainLayout>{children}</MainLayout>
      </div>
      </body>
    </html>
  );
}
